### ISSUE TITLE
New POS tags and attachment Labels

### ISSUE THREAD

**Issue by Sharefah-Alghamdi** [danifg/Left2Right-Pointer-Parser#3]
Hi
Thank you for sharing your code!
Kindly, I need your help with the following issue:

I'm trying to run your code with my own dataset and pos tags and labels.
but I got this  error:

Traceback (most recent call last):
  File "scripts/L2RParser.py", line 576, in <module>
    main()
  File "scripts/L2RParser.py", line 161, in main
    data_dev = conllx_stacked_data.read_stacked_data_to_variable(dev_path, word_alphabet, char_alphabet, pos_alphabet, type_alphabet, use_gpu=use_gpu, volatile=True, prior_order=prior_order)
  File "./neuronlp2/io/conllx_stacked_data.py", line 139, in read_stacked_data_to_variable
    data, max_char_length = read_stacked_data(source_path, word_alphabet, char_alphabet, pos_alphabet, type_alphabet, max_size=max_size, normalize_digits=normalize_digits, prior_order=prior_order)
  File "./neuronlp2/io/conllx_stacked_data.py", line 124, in read_stacked_data
    stacked_heads, children, siblings, stacked_types, skip_connect, previous, next = _generate_stack_inputs(inst.heads, inst.type_ids, prior_order)
  File "./neuronlp2/io/conllx_stacked_data.py", line 85, in _generate_stack_inputs
    siblings.append(sibs[head])
IndexError: list index out of range

**Comment by danifg** [comment]
It seems that your dataset hasn't the proper format. Please check that it follows the CoNLL format.

**Comment by Sharefah-Alghamdi** [comment]
> It seems that your dataset hasn't the proper format. Please check that it follows the CoNLL format.


The format is CoNLL!
The problem was that I removed the first token for the first sentence in the Dev file by mistake 

It works now!

Thank you for your help!
